### ISSUE TITLE
Internal error when running the mapping

### ISSUE THREAD

**Issue by Brainchain09** [RMLio/rmleditor-ce#9]
### Description
Whenever I try to run a mapping I made, with any .csv file I use, I get an internal server error.

### Steps

Import a .csv file. Add any entity from the columns. Try to run the mapping. 

### Environment

I have had this issue with the latest version of Firefox, Google Chrome and Safari as well.

**Comment by pheyvaer** [comment]
Hi @Brainchain09,

Can you provide us with a minimal failing example?

**Comment by Brainchain09** [comment]
Of course. Here is an example. I take this csv file, which I import in RMLEditor. The import seems to work properly, I have fields header which appear and the preview of the file shows no issue. I try to take a column (for instance Name) and drop in the mapping editor, and select New entity. I assign a prefix before {Name}, and then try to run the mapping. It fails with message "Internal server when executing remote RMLMapper".

[Item.csv](https://github.com/user-attachments/files/17930631/Item.csv)

**Comment by robertmuil** [comment]
Having this problem also.

Failing data is a very simple CSV:
```
Wording,ID
Blah,1
Bloop,2
```

Seeing this in Inspect Console:
> Not Found
> 404
> Error: Not Found
>     at /rmlmapper-webapi-js/app.js:93:17
>     at Layer.handle [as handle_request] (/rmlmapper-webapi-js/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/rmlmapper-webapi-js/node_modules/express/lib/router/index.js:328:13)
>     at /rmlmapper-webapi-js/node_modules/express/lib/router/index.js:286:9
>     at Function.process_params (/rmlmapper-webapi-js/node_modules/express/lib/router/index.js:346:12)
>     at next (/rmlmapper-webapi-js/node_modules/express/lib/router/index.js:280:10)
>     at /rmlmapper-webapi-js/node_modules/express/lib/router/index.js:646:15
>     at next (/rmlmapper-webapi-js/node_modules/express/lib/router/index.js:265:14)
>     at Function.handle (/rmlmapper-webapi-js/node_modules/express/lib/router/index.js:175:3)
>     at router (/rmlmapper-web
> api-js/node_modules/express/lib/router/index.js:47:12)

**Comment by robertmuil** [comment]
And this:
```
{
    "message": "Error while executing the rules.",
    "log": "16:20:37.393 [main] ERROR be.ugent.rml.cli.Main               .run(423) - Unrecognised content type: application/octet-stream\n",
    "stack": "Error: Error while executing the rules.\n    at ChildProcess.<anonymous> (/rmlmapper-webapi-js/node_modules/@rmlio/rmlmapper-java-wrapper/lib/wrapper.js:204:23)\n    at ChildProcess.emit (node:events:514:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:305:5)"
}
```

**Comment by robertmuil** [comment]
Also BTW, verified that the exported mapping for the data does work fine with the java `rmlmapper` offline.

**Comment by pheyvaer** [comment]
I can reproduce the error on my side. I will see if I can find out where it goes wrong.

**Comment by pheyvaer** [comment]
@Brainchain09 @robertmuil The issue is fixed at https://app.rml.io/rmleditor/.

**Comment by robertmuil** [comment]
Hey @pheyvaer - thanks muchly for the attention, unfortunately it still gives me the same error...

**Comment by pheyvaer** [comment]
@robertmuil Can you share a screen recording of the error?
